# Site settings
title: "Seabilwe P.L. Tilodi | GIS Analyst"
description: "My personal resume and portfolio demonstrating my GIS expertise and projects."
url: "https://yourusername.github.io"  # Replace with your GitHub Pages URL
baseurl: ""  # Leave empty if deploying at the root

# Build settings
theme: jekyll-theme-cayman
markdown: kramdown

# Optional: Enable plugins (e.g., RSS feed)
plugins:
  - jekyll-feed

# Customization options (optional)
# You can add additional configuration for the theme here.
# For example, to customize the navigation menu, you might add:
# navigation:
#   - title: "Profile"
#     url: "/#profile"
#   - title: "Experience"
#     url: "/#experience"
#   - title: "Education"
#     url: "/#education"
#   - title: "Projects"
#     url: "/#projects"
#   - title: "Skills"
#     url: "/#skills"
#   - title: "Languages"
#     url: "/#languages"
#   - title: "References"
#     url: "/#references"
