name: Deploy – Production
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # If you have a build step later (e.g. npm run build), insert it here
      # - run: npm ci && npm run build

      - name: Deploy to gh-pages (root)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # Pages publishing branch
          folder: .               # deploy the repo root (or ./build if you build)
          force: false
          clean: true
          clean-exclude: |
            pr-preview/
            staging/
