name: Deploy – Production
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # add a build step here later if you have one
      - name: Deploy to gh-pages (root)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .                 # or ./build if you build
          force: false
          clean: true
          # NOTE: no inline comments here either
          clean-exclude: |
            pr-preview/
            staging/
