name: PR Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
permissions:
  contents: write
concurrency: preview-${{ github.ref }}
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # add a build step here later if you ever have one
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
